### 1.1 Bayes’ Theorem: Dining Safely
99% of the restaurants in Kentish Town practice good hygiene. Each time you eat in a clean
restaurant, there is a 1% chance that you will get sick, independent of your previous visits.
Each time you eat in a restaurant that does not practice good hygiene, on the other hand,
there is a 50% chance that you will get sick, independent of your previous visits.
#### 1. You eat at a restaurant in Kentish Town and you get sick. What is the probability that the restaurant practices good hygiene?

**Hint:** Using the law of total probability, first calculate the probability of the event ‘falling sick’. You can use this probability in your subsequent application of Bayes’ Theorem.

**ANSWER**

    P(restaurant clean) = 0.99
    P(restaurant not clean) = 0.01
    P(falling sick|restaurant clean) = 0.01
    P(falling sick|restaurant not clean) = 0.50
    
    P(restaurant clean | falling sick)
    = (P(falling sick|restaurant clean) * P(restaurant clean)) / P(falling sick)
    = (P(falling sick|restaurant clean) * P(restaurant clean)) / ((P(falling sick|restaurant clean) * P(restaurant clean)) + (P(falling sick|restaurant not clean) * P(restaurant not clean)))
    = (0.01 * 0.99) / ((0.01*0.99) + (0.50*0.01))
    = 0.0099 / (0.0099 + 0.0050)
    = 0.0099 / 0.0149
    = 0.6644
    = 66.44% chance

#### 2. You go to the same restaurant for a second time, and you get sick again. What is the probability of the restaurant practicing good hygiene now?

**Hint:** Using the law of total probability, first calculate the probability of the event ‘falling sick twice’. In this calculation, you can use the conditional independences 
    
    P(falling sick twice|restaurant clean) = P(falling sick once|restaurant clean)
and
    
    P(falling sick twice|restaurant not clean) = P(falling sick once|restaurant not clean)
    
You can use these probabilities in your subsequent application of Bayes’ Theorem, where
you can again use the same conditional independence.
    
**ANSWER:** Here we'll use restaurant clean probability calculated from previous stage:
  
    P(restaurant clean) = 0.99
    P(restaurant not clean) = 0.01
    P(falling sick|restaurant clean) = 0.01
    P(falling sick|restaurant not clean) = 0.50
    
    
    P(restaurant clean | falling sick twice)
    = (P(falling sick twice|restaurant clean) * P(restaurant clean)) / P(falling sick twice)
    = (P(falling sick twice|restaurant clean) * P(restaurant clean)) / ((P(falling sick twice|restaurant clean) * P(restaurant clean)) + (P(falling sick twice|restaurant not clean) * P(restaurant not clean)))
    = (P(falling sick once|restaurant clean) * P(falling sick once|restaurant clean) * P(restaurant clean)) / ((P(falling sick once|restaurant clean) * P(falling sick once|restaurant clean) * P(restaurant clean)) + (P(falling sick once|restaurant not clean)* P(falling sick once|restaurant not clean) * P(restaurant not clean)))
    = (0.01 * 0.01 * 0.99) / ((0.01 * 0.01 * 0.99) + (0.5 * 0.5 * 0.01))
    = 0.000099 / (0.000099 +  0.0025)
    = 0.0099 / 0.002599
    = 0.03809
    = 3.80% chance

### 1.2 Building a Spam Filter
Consider the following 4 SMS messages and their classification as ‘ham’ or ‘spam’ messages:

message | label
--------|------
I am not coming | ham
Good work | ham
Do you need viagra  | spam
win an IMac | spam

Using the above messages, construct a Na¨ıve Bayes classifier to classify new SMS messages. In particular:
#### 1. Compute the prior probabilities of a new SMS message being ‘spam’ or ‘ham’. (These are just the empirical probabilities from the four messages above.) 

**ANSWER:** These are just intial probabilities of message being Spam / Ham which is 50% initially for both.

Spam/Ham|Count/Freq|P(Spam/Ham)
-|-|-
Spam|2|2/4 = 0.5
Ham|2|2/4 = 0.5
-|-|-
Total|4|100.00%


#### 2. For each de-capitalised keyword that appears in your training set (that is, ‘i’, ‘am’, ‘not’, ‘coming’, ‘good’, ‘work’, ‘do’, ‘you’, ‘need’, ‘viagra’, ‘win’, ‘an’ and ‘imac’), build a frequency table that records the likelihoods P(W|ham), P(¬W|ham), P(W|spam) and P(¬W|spam)

**ANSWER:**

Word|Count/Freq|Spam|Ham|P(W - Spam)|P(W - Ham)|P(~W - Spam)|P(~W - Ham)
-|-|-|-|-|-|-|-
i|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
am|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
not|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
coming|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
good|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
work|1|0|1|0 = 0.05|1/6 = 0.166|1 -  0.05 = 0.95|1 -  0.166= 0.833
do|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
you|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
need|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
viagra|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
win|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
an|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
imac|1|1|0|1/7 = 0.142|0 = 0.05|1 -  0.142 = 0.858|1 -  0.05 = 0.95
-|-|-|-|-|-|-|-
Total|12|7|5|100.00%|100.00%


Now you can use the Na¨ıve Bayes algorithm to make predictions. Predict if the following two SMS messages are ham or spam:

message | label
--------|------
Coming home | ?
Get Viagra now | ?

**ANSWER**

We have above maintained small dictionary of words which appeared in messages when we trained our model. If we found that words in new upcoming messages then based on above probability tables we make prediction of new mail being spam/ham.

Prior Probabilites of message beng spam/ham is : `P(Spam) = 0.5` & `P(Ham) = 0.5`
    
**Message 1:** Coming home

Here only word `coming` appears in our words dictionary which we are maintaining above. Hence we'll make prediction based on this word appearing in message and whether it's spam/ham mail based on that.
    
    P(spam|¬i ∧ ¬am ∧ ¬not ∧ coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ ¬viagra ∧ ¬win ∧ ¬an ∧ ¬imac)
    ∝  P(spam)*P(¬i|spam)*P(¬am|spam)*P(¬not|spam)*P(coming|spam)*P(¬good|spam)*P(¬work|spam)*P(¬do|spam)*P(¬you|spam)*
    P(¬need|spam)*P(¬viagra|spam)*P(¬win|spam)*P(¬an|spam)*P(¬imac|spam)
    ∝ 0.50 * 0.95 * 0.95 * 0.95 * 0.05 * 0.95 * 0.95 * 0.858 * 0.858 * 0.858 * 0.858 * 0.858 * 0.858 * 0.858
    ∝ 0.006621
    
    P(ham|¬i ∧ ¬am ∧ ¬not ∧ coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ ¬viagra ∧ ¬win ∧ ¬an ∧ ¬imac)
    ∝ P(ham)*P(¬i|ham)*P(¬am|ham)*P(¬not|ham)*P(coming|ham)*P(¬good|ham)*P(¬work|ham)*P(¬do|ham)*P(¬you|ham)*
    P(¬need|ham)*P(¬viagra|ham)*P(¬win|ham)*P(¬an|ham)*P(¬imac|ham)
    ∝ 0.50 * 0.833 * 0.833 * 0.833 * 0.166 * 0.833 * 0.833 * 0.95 * 0.95 * 0.95 * 0.95 * 0.95 * 0.95 * 0.95
    ∝ 0.02790
    
We have now got near values for message being spam/ham. We'll now use normalization to convert them to probabilities (P(spam) + P(ham) = 1).
    
    p(spam) = 0.006621 / (0.00621 + 0.02790) = 0.006621 / 0.034521 = 0.1917
    p(ham)  = 0.02790  / (0.00621 + 0.02790) = 0.027900 / 0.034521 = 0.8082
    
**Message 2:** Get Viagra now

Here only word `viagra` appears in our words dictionary which we are maintaining above. Hence we'll make prediction based on this word appearing in message and whether it's spam/ham mail based on that.
    
    P(spam|¬i ∧ ¬am ∧ ¬not ∧ ¬coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ viagra ∧ ¬win ∧ ¬an ∧ ¬imac)
    ∝  P(spam)*P(¬i|spam)*P(¬am|spam)*P(¬not|spam)*P(¬coming|spam)*P(¬good|spam)*P(¬work|spam)*P(¬do|spam)*P(¬you|spam)*
    P(¬need|spam)*P(viagra|spam)*P(¬win|spam)*P(¬an|spam)*P(¬imac|spam)
    ∝ 0.50 * 0.95 * 0.95 * 0.95 * 0.95 * 0.95 * 0.95 * 0.858 * 0.858 * 0.858 * 0.142 * 0.858 * 0.858 * 0.858
    ∝ 0.0208
    
    P(ham|¬i ∧ ¬am ∧ ¬not ∧ ¬coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ viagra ∧ ¬win ∧ ¬an ∧ ¬imac)
    ∝ P(ham)*P(¬i|ham)*P(¬am|ham)*P(¬not|ham)*P(¬coming|ham)*P(¬good|ham)*P(¬work|ham)*P(¬do|ham)*P(¬you|ham)*
    P(¬need|ham)*P(viagra|ham)*P(¬win|ham)*P(¬an|ham)*P(¬imac|ham)
    ∝ 0.50 * 0.833 * 0.833 * 0.833 * 0.833 * 0.833 * 0.833 * 0.95 * 0.95 * 0.95 * 0.05 * 0.95 * 0.95 * 0.95
    ∝ 0.00613
    
We have now got near values for message being spam/ham. We'll now use normalization to convert them to probabilities (P(spam) + P(ham) = 1).
    
    p(spam) = 0.02080 / (0.0208 + 0.00613) = 0.02080 / 0.02693 = 0.7723
    p(ham)  = 0.00613 / (0.0208 + 0.00613) = 0.00613 / 0.02693 = 0.2276

**Hint**
This actually turns out to be more cumbersome than expected: For the first SMS message, for
example, you need to use the law of total probability as well as the conditional independence
to compute the quantity

    P(¬i ∧ ¬am ∧ ¬not ∧ coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ ¬viagra ∧ ¬win ∧ ¬an ∧ ¬imac).

Afterwards you can compute the quantities
    
    P(ham|¬i ∧ ¬am ∧ ¬not ∧ coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ ¬viagra ∧ ¬win ∧ ¬an ∧ ¬imac)
    
and

    P(spam|¬i ∧ ¬am ∧ ¬not ∧ coming ∧ ¬good ∧ ¬work ∧ ¬do ∧ ¬you ∧ ¬need ∧ ¬viagra ∧ ¬win ∧ ¬an ∧ ¬imac)

using Bayes’ Theorem and the conditional independence.

Alternatively, you can exploit (as explained in the slides) the fact that

    P(ham|¬i ∧ ¬am ∧ . . .) ∝ P(ham) · P(¬i|ham) · P(¬am|ham) · . . .
and

    P(spam|¬i ∧ ¬am ∧ . . .) ∝ P(spam) · P(¬i|spam) · P(¬am|spam) · . . .

to calculate propensities that you subsequently scale to probabilities by dividing them with
the sum

    P(ham) · P(¬i|ham) · P(¬am|ham) · . . . + P(spam) · P(¬i|spam) · P(¬am|spam) · . . .

You can use a spreadsheet to simplify computations if you wish. Make sure that you
explain every step, though!

In [60]:
%ls smsspamcollection

readme  SMSSpamCollection


### 2 Assignment #2
For this group assignment, download the SMS Spam Collection data set from
    
    https://archive.ics.uci.edu/ml/machine-learning-databases/00228/

and follow the steps below to build a Na ̈ıve Bayes spam filter.

In [61]:
#!cat smsspamcollection/SMSSpamCollection

In [62]:
import pandas as pd
import numpy as np
import matplotlib as plt

import sklearn
from sklearn.model_selection import train_test_split

import re
import collections

#### 1. Load the data into a Python data frame.

In [63]:
df = pd.read_csv('smsspamcollection/SMSSpamCollection', names = ['Spam/Ham','Mail'], sep='\t')
df.head()

Spam/Ham                                               Mail
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

#### 2. Pre-process the SMS messages: Remove all punctuation and numbers from the SMS messages, and change all messages to lower case. (Please provide the Python code that achieves this!)

In [64]:
df['Mail'] = [mail.lower() for mail in df['Mail']]
df.head()

Spam/Ham                                               Mail
0      ham  go until jurong point, crazy.. available only ...
1      ham                      ok lar... joking wif u oni...
2     spam  free entry in 2 a wkly comp to win fa cup fina...
3      ham  u dun say so early hor... u c already then say...
4      ham  nah i don't think he goes to usf, he lives aro...

In [65]:
regex = re.compile(r'[a-z]+')
df['Mail'] = [' '.join(regex.findall(mail)) for mail in df['Mail']]
df.head()

Spam/Ham                                               Mail
0      ham  go until jurong point crazy available only in ...
1      ham                            ok lar joking wif u oni
2     spam  free entry in a wkly comp to win fa cup final ...
3      ham        u dun say so early hor u c already then say
4      ham  nah i don t think he goes to usf he lives arou...

In [66]:
x = np.arange(len(df))
print(x[:10])
print(x.shape)
rand = np.random.RandomState(123)
rand.shuffle(x)
print(x[:10])
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(5572,)
[3237  843 3521 2123  738  923 2977 4623 4388 4931]
(5572,)


In [67]:
df = df.iloc[x]
df.head()

Spam/Ham                                               Mail
3237      ham  aight text me when you re back at mu and i ll ...
843       ham  our prashanthettan s mother passed away last n...
3521      ham  no it will reach by only she telling she will ...
2123      ham                        do you know when the result
738      spam  hi customer loyalty offer the new nokia mobile...

#### 3. Shuffle the messages and split them into a training set (2,500 messages), a validation set (1,000 messages) and a test set (all remaining messages).

In [68]:
X_train, X_val, Y_train, Y_val = train_test_split(df['Mail'].values, df['Spam/Ham'].values, 
                                                                   train_size=2500, test_size = len(df) - 2500,
                                                                   stratify= df['Spam/Ham'].values)
X_val, X_test, Y_val, Y_test = train_test_split(X_val,Y_val, 
                                                train_size = 1000, test_size = len(Y_val) - 1000,
                                                stratify=Y_val)
X_train.shape, Y_train.shape, X_val.shape, Y_val.shape, X_test.shape, Y_test.shape

((2500,), (2500,), (1000,), (1000,), (2072,), (2072,))

In [69]:
collections.Counter(df['Spam/Ham'].values), collections.Counter(Y_train), collections.Counter(Y_val), collections.Counter(Y_test)

(Counter({'ham': 4825, 'spam': 747}),
 Counter({'ham': 2165, 'spam': 335}),
 Counter({'spam': 134, 'ham': 866}),
 Counter({'ham': 1794, 'spam': 278}))

#### 4. While Python’s SciKit-Learn library has a Na ̈ıve Bayes classifier, it works with continuous probability distributions and assumes numerical features. Although it is possible to transform categorical variables into numerical features using a binary encoding, we will instead build a simple Na ̈ıve Bayes classifier from scratch:

In [70]:
class NaiveBayesForSpam :
    def train(self , hamMessages , spamMessages ) :
        self.words = set(' '.join(hamMessages + spamMessages).split())
        self.priors = np.zeros(2)
        self.priors[0] = float(len(hamMessages)) / (len(hamMessages) +  len(spamMessages))
        self.priors[1] = 1.0 - self.priors[0]
        self.likelihoods = []
        for i,w in enumerate(self.words):
            prob1 = (1.0 + len([m for m in hamMessages if w in m])) / len(hamMessages)
            prob2 = (1.0 + len( [m for m in spamMessages if w in m])) / len(spamMessages)
            self.likelihoods.append([min(prob1, 0.95) , min(prob2 , 0.95)])
        self.likelihoods = np.array(self.likelihoods).T
            
    def train2(self,hamMessages,spamMessages, times=20):
        self.words = set(' '.join(hamMessages + spamMessages).split())
        self.priors = np.zeros(2)
        self.priors[0] = float(len(hamMessages)) / (len(hamMessages) + len(spamMessages))
        self.priors[1] = 1.0 - self.priors[0]
        self.likelihoods = []
        spamkeywords = []
        for i,w in enumerate(self.words):
            prob1 = (1.0 + len([m for m in hamMessages if w in m])) / len(hamMessages)
            prob2 = (1.0 + len([m for m in spamMessages if w in m])) / len(spamMessages)
            if prob1 * times < prob2 :
                self.likelihoods.append([min(prob1 , 0.95) , min(prob2 , 0.95)])
                spamkeywords.append(w)
        self.words = spamkeywords
        self.likelihoods = np.array(self.likelihoods).T

    def predict(self , message):
        posteriors = np.copy(self.priors)
        for i,w in enumerate(self.words):
            if w in message.lower() : #convert to lower−case
                posteriors *= self.likelihoods[:,i]
            else:
                posteriors *= np.ones(2) - self.likelihoods[:,i]
            posteriors = posteriors / np.linalg.norm(posteriors , ord = 1) # normalise
        if posteriors[0] > 0.5:
            return ['ham', posteriors[0]]
        return ['spam ', posteriors[1]]
    
    def score(self,messages,labels):
        confusion = np.zeros(4).reshape(2,2)
        for m,l in zip(messages,labels):
            if self.predict(m)[0] == 'ham' and l == 'ham':
                confusion[0,0] += 1
            elif self.predict(m)[0] == 'ham' and l == 'spam':
                confusion[0,1] += 1
            elif self.predict(m)[0] == 'spam' and l == 'ham':
                confusion[1,0] += 1
            elif self.predict(m)[0] == 'spam' and l == 'spam':
                confusion[1,1] += 1
        return (confusion[0,0] + confusion[1,1])/float(confusion.sum()) , confusion

#### 5. Explain the code: What is the purpose of each function? What do ’train’ and ‘train2’ do, and what is the difference between them? Where in the code is Bayes’ Theorem being applied?

We have defined class named `NaiveBayesForSpam` which holds 4 methods `(train, train2, predict, score)`.

* `train()` - It takes 2 arguments as input. First argument is list of ham messages and second argument is list of spam messages. When this method is called it loops through each of the word of ham and spam messages and creates likelihood for each word. It maintains probability for each word which will be how much it contributes to prediction(spam/ham) if that word occurs in message.It also maintains prior probabilities as well for spam and ham messages which is how much percentage of total mails as spam and how much are ham.
* `train2()` - It takes 2 arguments as input. First argument is list of ham messages and second argument is list of spam messages. When this method is called it loops through each of the word of ham and spam messages and creates likelihood for only word where probability of word in spam mail is being high. Its only maintaining words which are commonly occuring in spam messages than maintaining list of all words from ham messages as well. It maintains probability for each word which will be how much it contributes to prediction(spam/ham) if that word occurs in message. It also maintains prior probabilities as well for spam and ham messages which is how much percentage of total mails as spam and how much are ham.
* `predict()` - It takes as input message to be classified as spam/ham. This method loops through all words maintained during training and using Naive Bayes predicts probability of messsage being spam/ham. It returns list where first string is spam/ham and second value of list is probability of it being spam/ham.
* `score()` - It takes as input 2 arguments. First argument is list of messages and 2nd argument is actual labels(spam/ham) for each message. It loops through each messages and predicts whether it's spam/ham using `predict()` method. It also maintains confusion matrix using actual lables provided as input. It then calculates accuracy of model on list of messages provided as input. It returns accuracy of model on list of messages and confusion matrix as list.

Confusion Matrix = 

                    [[TP, FN],
                    [FP, TN]]

`predict()` method has actual implementation of NaiveBayes theorem where we are using likelihoods calculated during training and based on that getting near values for message being spam/ham. Using this near values, we calculate probabilities using normalisation.

#### 6. Use your training set to train the classifiers ‘train’ and ‘train2’. Note that the interfaces of our classifiers require you to pass the ham and spam messages separately.

In [71]:
%%time
naive_bayes_classifier = NaiveBayesForSpam()
naive_bayes_classifier.train(X_train[Y_train == 'ham'].tolist(), X_train[Y_train == 'spam'].tolist())
print('Total Words : ', len(naive_bayes_classifier.words))
print('First Few Words : ',list(naive_bayes_classifier.words)[:10])

Total Words :  5131
First Few Words :  ['samantha', 'unfortunately', 'senses', 'another', 'indians', 'praveesh', 'anyway', 'triumphed', 'understood', 'their']
CPU times: user 2.56 s, sys: 0 ns, total: 2.56 s
Wall time: 2.56 s


In [72]:
%%time
naive_bayes_classifier2 = NaiveBayesForSpam()
naive_bayes_classifier2.train2(X_train[Y_train == 'ham'].tolist(), X_train[Y_train == 'spam'].tolist())
print('Total Words : ', len(naive_bayes_classifier2.words))
print('First Few Words : ',list(naive_bayes_classifier2.words)[:10])

Total Words :  204
First Few Words :  ['statement', 'freefone', 'order', 'services', 'pod', 'ae', 'truly', 'motorola', 'orange', 'bluetooth']
CPU times: user 2.56 s, sys: 0 ns, total: 2.56 s
Wall time: 2.56 s


In [73]:
%%time
naive_bayes_classifier3 = NaiveBayesForSpam()
naive_bayes_classifier3.train2(X_train[Y_train == 'ham'].tolist(), X_train[Y_train == 'spam'].tolist(), 10) ##Notice times parameter
print('Total Words : ', len(naive_bayes_classifier3.words))
print('First Few Words : ',list(naive_bayes_classifier3.words)[:10])

Total Words :  793
First Few Words :  ['customers', 'statement', 'marley', 'calls', 'freefone', 'java', 'order', 'services', 'pod', 'doubletxt']
CPU times: user 2.97 s, sys: 0 ns, total: 2.97 s
Wall time: 2.98 s


In [74]:
%%time
naive_bayes_classifier4 = NaiveBayesForSpam()
naive_bayes_classifier4.train2(X_train[Y_train == 'ham'].tolist(), X_train[Y_train == 'spam'].tolist(), 25) ##Notice times parameter
print('Total Words : ', len(naive_bayes_classifier4.words))
print('First Few Words : ',list(naive_bayes_classifier4.words)[:10])

Total Words :  186
First Few Words :  ['statement', 'freefone', 'services', 'pod', 'ae', 'truly', 'motorola', 'orange', 'bluetooth', 'discount']
CPU times: user 2.54 s, sys: 0 ns, total: 2.54 s
Wall time: 2.54 s


#### 7. Using the validation set, explore how each of the two classifiers performs out of sample.

In [75]:
%%time
accuracy_val1, confusion_mat_val1 = naive_bayes_classifier.score(X_val.tolist(), Y_val.tolist())

CPU times: user 9min 9s, sys: 111 ms, total: 9min 9s
Wall time: 9min 9s


In [76]:
print('Validation Accuracy : ',accuracy_val1)
print('Confusion Matrix : ')
confusion_mat_val1

Validation Accuracy :  0.9803012746234068
Confusion Matrix : 


array([[846.,  17.],
       [  0.,   0.]])

In [77]:
%%time
accuracy_val2, confusion_mat_val2 = naive_bayes_classifier2.score(X_val.tolist(), Y_val.tolist())

CPU times: user 20.8 s, sys: 0 ns, total: 20.8 s
Wall time: 20.8 s


In [78]:
print('Validation Accuracy : ',accuracy_val2)
print('Confusion Matrix : ')
confusion_mat_val2

Validation Accuracy :  0.9706214689265537
Confusion Matrix : 


array([[859.,  26.],
       [  0.,   0.]])

In [79]:
%%time
accuracy_val3, confusion_mat_val3 = naive_bayes_classifier3.score(X_val.tolist(), Y_val.tolist())

CPU times: user 1min 19s, sys: 4 ms, total: 1min 19s
Wall time: 1min 19s


In [80]:
print('Validation Accuracy : ',accuracy_val3)
print('Confusion Matrix : ')
confusion_mat_val3

Validation Accuracy :  0.9707865168539326
Confusion Matrix : 


array([[864.,  26.],
       [  0.,   0.]])

In [81]:
%%time
accuracy_val4, confusion_mat_val4 = naive_bayes_classifier4.score(X_val.tolist(), Y_val.tolist())

CPU times: user 18.9 s, sys: 4 ms, total: 18.9 s
Wall time: 18.9 s


In [82]:
print('Validation Accuracy : ',accuracy_val4)
print('Confusion Matrix : ')
confusion_mat_val4

Validation Accuracy :  0.971655328798186
Confusion Matrix : 


array([[857.,  25.],
       [  0.,   0.]])

#### 8. Why is the ‘train2’ classifier faster? Why does it yield a better accuracy both on the training and the validation set?
As a part of `train2()` method, we are only maintaining words which are part of spam messages and contribute to message being spam with high probability. Words getting maintained as part of classified trained using this methods will be less compared to `train()`. Using these words we can guess with high probability of message being spam. Also its better to keep message as ham if model is less sure about message being spam. This way important mail won't end up in spam folder if classifier is less confident about message being spam like around 0.6-0.7 probability.

#### 9. How many false positives (ham messages classified as spam messages) did you get in your validation set? How would you change the code to reduce false positives at the expense of possibly having more false negatives (spam messages classified as ham messages)?

We are getting 0 false positives(ham messages getting classified as spam messages). All messages are getting classified as ham due to high majority of ham messages and model overfitting.

We can modify `if` statement in `train2()` method to change proportion of comparision between `prob1` & `prob2`. We have modified code above to pass one extra argument to `train2()` method. We have above created 2 another model with values more and less then default 20 times. Using more values for parameter `times` values results in taking only those words for which our model is more sure to be part of spam messages. More value for parameter spam will result in having more false negatives and less false positives.

#### 10. Run the ‘train2’ classifier on the test set and report its performance using a confusion matrix.

In [83]:
%%time
accuracy_test2, confusion_mat_test2 = naive_bayes_classifier2.score(X_test.tolist(), Y_test.tolist())

CPU times: user 43 s, sys: 0 ns, total: 43 s
Wall time: 43 s


In [84]:
print('Test Accuracy : ',accuracy_test2)
print('Confusion Matrix : ')
confusion_mat_test2

Test Accuracy :  0.9747668678003292
Confusion Matrix : 


array([[1777.,   46.],
       [   0.,    0.]])

In [85]:
%%time
accuracy_test3, confusion_mat_test3 = naive_bayes_classifier3.score(X_test.tolist(), Y_test.tolist())

CPU times: user 2min 45s, sys: 7.99 ms, total: 2min 45s
Wall time: 2min 45s


In [86]:
print('Test Accuracy : ',accuracy_test3)
print('Confusion Matrix : ')
confusion_mat_test3

Test Accuracy :  0.9781540141998908
Confusion Matrix : 


array([[1791.,   40.],
       [   0.,    0.]])

In [87]:
%%time
accuracy_test4, confusion_mat_test4 = naive_bayes_classifier4.score(X_test.tolist(), Y_test.tolist())

CPU times: user 39.1 s, sys: 3.99 ms, total: 39.1 s
Wall time: 39.1 s


In [88]:
print('Test Accuracy : ',accuracy_test4)
print('Confusion Matrix : ')
confusion_mat_test4

Test Accuracy :  0.9726177437020811
Confusion Matrix : 


array([[1776.,   50.],
       [   0.,    0.]])